### ISSUE TITLE
Looking for new maintainers 💛

### ISSUE THREAD

**Issue by FrancesCoronel** [FrancesCoronel/apprenticeships.me#257]
Hey folks, @benjaminmodayil and I are super busy with work these days and haven't been able to actively maintain this project as much as it deserves. 

If anyone is interested in taking this up, we can add you to the Netlify instance and give you admin rights for the repo. 

Let us know!

**Comment by changangus** [comment]
Hey Frances,

Let me know if you still need help and if so I'd love to contribute in any way that I can.

**Comment by FrancesCoronel** [comment]
@benjaminmodayil Any objections to having Anugs help with maintenance? 😄

**Comment by benjaminmodayil** [comment]
@FrancesCoronel  Not sure how I missed this! No issue from my end. Let me know how I can help, Angus.

**Comment by FrancesCoronel** [comment]
@changangus I sent over an invite - the primary need is keeping packages up to date + adding in new apprenticeships anytime you see one as they pop up.

**Comment by changangus** [comment]
Hey All,

Sorry for the late response! I got the invite and will get started on some of the PRs. I'll be sure to reach out if I have any questions. 

Thanks!

**Comment by benjaminmodayil** [comment]
@changangus Feel free to reach out to me via the email in my Github profile if I'm not super responsive here or you need help on anything. For some reason I don't get half of my Github notifications.

**Comment by changangus** [comment]
@benjaminmodayil 
Thanks! I'll reach out when I have some questions for sure
