### ISSUE TITLE
Add: The Urban Technology Project

### ISSUE THREAD

**Issue by benjaminmodayil** [FrancesCoronel/apprenticeships.me#279]
## Company

The Urban Technology Project

## Description

The Urban Technology Project (UTP) is hiring for the next cohort of I.T. Apprentices.  In partnership with the School District of Philadelphia & Communities in School of Philadelphia, 
UTP offers two I.T. Apprenticeships for individuals interested in pursuing careers in I.T. 
For young adults with 1yr of I.T. experience or 1 I.T. certification interested in pursuing a career in Tech, apply now for the Registered I.T. Apprenticeship, Computer Support Specialist role.  Computer Support Specialists work alongside School District Technology Teachers to support the overall technology needs of the school.  In this role you will earn as you learn through on-the-job experience, mentorship and technical training. This is a full-time I.T. Apprenticeship which includes benefits such as I.T. certifications, monthly transpass and a salary with benefits. To learn more about the Computer Support Specialist, I.T. Apprenticeship visit our website at utp-philly.org

## Link

http://utp-philly.org/

## Location

Philadelphia, Pa

*This entry was submitted by the form on the site*

**Comment by FrancesCoronel** [comment]
@changangus would you be able to add this in? 😄

**Comment by changangus** [comment]
@FrancesCoronel It looks like this apprenticeship was already added in! Just wanted to let you know before I close the issue.

**Comment by FrancesCoronel** [comment]
Got it thanks for the heads up
