### ISSUE TITLE
Do these apprenticeships actually work?

### ISSUE THREAD

**Issue by galaxyhaxz** [FrancesCoronel/apprenticeships.me#341]
I was excited to stumble upon the apprenticeships.me website earlier this year and applied to 2 different entry level programs. Didn't hear back from either of them, emailed them, still didn't hear back. Do they actually take the time to review and contact people?

Are these all only seasonal as well? Currently I don't see any openings. I missed the apps in April/May so I presume they do them twice a year?

Thanks for your work on the project thus far and hope to find a job in tech for once, as a self-taught dev.

**Comment by changangus** [comment]
Hey @galaxyhaxz! 

I can't speak for every posting on the site, but I believe the majority of the postings are seasonal and you may or may not hear back from the company (we have no control over that aspect). I can say that I personally have gotten a position from a company that is listed on the site, that being said the timing aspect is difficult, I would check the companies you are most interested in frequently. Also, don't forget to check their company websites, especially if one of the links happens to be broken (and please let us know if that is the case by opening an issue so we can fix it!). If you have any other questions feel free to ask, if I don't know the answer I can direct you to one of the main maintainers of this repo.

**Comment by galaxyhaxz** [comment]
I believe I've only ran into one broken link thus far. Google, IBM, Apple, and Microsoft all have programs but they closed apps in mid-May. I'll keep checking back and apply when something comes up.

Thanks for the help, best of luck.
