### ISSUE TITLE
Add: 

### ISSUE THREAD

**Issue by ttshehlane** [FrancesCoronel/apprenticeships.me#407]
## Company

INKFISH digital marketing

## Description

INKFISH provides a learning platform where individuals from all walks of life are overseen by a quality-driven team of experts, ensuring your brand, website, and digital marketing. Participating in a web design and SEO apprenticeship will provide you with the opportunity to work for real clients under professional supervision. Time management and communication are vital to this position, as you will need to follow directions and be a contributing member of the INKFISH team. You will work in the web design department learning the ins and outs of SEO best practices and how to properly incorporate this into optimized web content.

## Link

https://inkfish.digital/academy-2/web-team/

## Location

Remote

## Featured Image

https://inkfish.digital/wp-content/uploads/2021/09/INKFISH-web-team-banner.jpg

---

> By submitting this issue, I have verified the following ✅

- [] Checked to see if the apprenticeship has already been added before 🤔️
- [] Made sure all the details were provided 🔍️

**Comment by FrancesCoronel** [comment]
@changangus this looks like it qualifies!
