### ISSUE TITLE
Bug: the apprenticeship website seems to be down

### ISSUE THREAD

**Issue by helenamwu** [FrancesCoronel/apprenticeships.me#447]
## To Reproduce

1. Go to https://apprenticeships.me/
2. See error

## Expected behavior

A database/table/chart of many different apprenticeships and their info

## Screenshots

Instead, we see this: https://share.getcloudapp.com/YEuBLeGN

## Desktop (if applicable)

- OS: MacOS 12.2.1
- Browser: Google Chrome
- Version: Google Chrome Version 98.0.4758.109 (Official Build) (arm64)

## Smartphone (if applicable)

- Browser [e.g. Chrome, Safari]

**Comment by FrancesCoronel** [comment]
Looks like this was resolved already! cc @changangus
