### ISSUE TITLE
Add: Airbnb

### ISSUE THREAD

**Issue by zliwow** [FrancesCoronel/apprenticeships.me#521]
## Company

Airbnb

## Description

Airbnb operates an online marketplace focused on short-term homestays and experiences.

## Link

https://ourcollective.us/airbnb-connect-software-engineering-apprenticeship/

## Location

San Francisco Bay Area

## Featured Image
https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg

Thanks for reading my issue.

**Comment by FrancesCoronel** [comment]
@zliwow Thanks for sharing this apprenticeship! Do you know if there's a new iteration of this apprenticeship available? Looks like the application deadline already passed back in early 2022, and it's unclear if this will repeat again.

**Comment by zliwow** [comment]
Thanks for addressing my issue. You are correct, a the moment, Airbnb hasn't updated it. Though their apprenticeship is a known program, I thought I put it out there so people can keep an eye out for potential updates.

**Comment by zliwow** [comment]
> @zliwow Thanks for sharing this apprenticeship! Do you know if there's a new iteration of this apprenticeship available? Looks like the application deadline already passed back in early 2022, and it's unclear if this will repeat again.

Thanks for addressing my issue. You are correct, a the moment, Airbnb hasn't updated it. Though their apprenticeship is a known program, I thought I put it out there so people can keep an eye out for potential updates.

**Comment by FrancesCoronel** [comment]
> > @zliwow Thanks for sharing this apprenticeship! Do you know if there's a new iteration of this apprenticeship available? Looks like the application deadline already passed back in early 2022, and it's unclear if this will repeat again.
> 
> Thanks for addressing my issue. You are correct, a the moment, Airbnb hasn't updated it. Though their apprenticeship is a known program, I thought I put it out there so people can keep an eye out for potential updates.

Makes sense, thanks for sharing! I'll add it in when I have a chance! 👍🏽
