### ISSUE TITLE
Edit

### ISSUE THREAD

**Issue by Will513r** [FrancesCoronel/apprenticeships.me#570]
Insert description of issue here

---When looking for the credits section in the read me it is actually the ## Contributors section which created confusion

![Screenshot (66)](https://user-images.githubusercontent.com/111171001/219466959-af20fd3c-a7e8-40c4-8f83-9da03dec2e9c.png)

**Comment by FrancesCoronel** [comment]
@Will513r Thanks for flagging. I went ahead and updated the wording here.
